#!/usr/bin/env bash
#
# Author: Barret E (2026) <https://github.com/archusXIV/fzfm>
# Script name: fzfm v0.2.7
# License: GPLv2
#
# A simple terminal file manager using fzf, with expected functionalities
# - copy/paste, move, rename, create, edit, delete files
# - bookmarks support
# Navigate directories with fzf selection previews update dynamically.
# Dependencies: bat, chafa and tree for previews and programs determined in ~/.config/fzfm/fzfmrc
# Press Ctrl-C or ESC in fzf to exit.

# shellcheck disable=SC2154
# shellcheck source=/dev/null
# Needed if your shell isn't bash,
# this will set the bash shell only in the terminal session.
export SHELL="/bin/bash"
shopt -s checkwinsize

version="v0.2.7"
script_name=$(basename "$0")
config_dir="$HOME/.config/fzfm"
config="$config_dir/fzfmrc"
ascii_file="$config_dir/fzfm_ascii"
book_marks="$config_dir/fzfm_bookmarks"

# shell syntax for prompts
red=$'\e[31m'
grn=$'\e[32m'
ylw=$'\e[33m'
cyn=$'\e[36m'
noc=$'\e[0m'
bold=$'\e[1m'
nobold=$'\e[21m'

if [[ -f $config ]]; then
    source "$config"
else
    printf '%s\n' " ${red}$config: no such file or directory.${noc}"
    exit 127
fi

_usage() {
    tput clear
    echo
    cat <<- USAGE
    =========================================================================
    A TERMINAL BASED SIMPLE FILEMANAGER USING FZF WITH BASIC EXPECTED OPTIONS
    =========================================================================
    If no option provided then $script_name uses $config
    Press Ctrl-C or ESC to exit.

    Available options:
    -e <editor>       :Set your editor for editing files (default:vim).
    -f <program>      :Set a program to get infos from selected file (default:exiftool).
    -h|--help         :Print this message and exit.
    -i <image viewer> :Set a program to open image files (default:sxiv).
    -m <program>      :Set a program to get infos from selected media file (default:mediainfo).
    -p <player>       :Set a program to play selected media file (default:mpv).

    Example:
    $script_name -e nano -i feh -f exiftool -m mediainfo -p vlc
USAGE
    exit 1
}

[[ $1 =~ -h|--help ]] && _usage

# Parsing command-line options
while getopts "e:f:i:m:p:" opt; do
    case $opt in
        e) FZFM_EDITOR="$OPTARG" ;;
        f) FILE_INFO="$OPTARG" ;;
        i) IMAGE_VIEWER="$OPTARG" ;;
        m) MEDIA_INFO="$OPTARG" ;;
        p) MEDIA_PLAYER="$OPTARG" ;;
        *) _usage ;;
    esac
done

shift $(( OPTIND - 1 ))

# Ensure required tools and files are installed
declare -a deps=(
    bat chafa df fzf stat tree
    "$IMAGE_VIEWER" "$FILE_INFO"
    "$FZFM_EDITOR" "$MEDIA_INFO"
    "$ascii_file" "$book_marks"
)

for dep in "${deps[@]:0:10}"; do
    command -v "$dep" >/dev/null || {
        echo "$dep is needed but not installed, exiting..."
        exit 127
    }
done

for dep in "${deps[@]:10:11}"; do
    [[ ! -f $dep ]] && {
        echo "${dep##*/} is needed but does not exist, exiting..."
        exit 127
    }
done

_mediaPlayer() {
    local media_file=$1
    # Media player should run outside of the menu (detatched from the terminal),
    # so that we stay in the menu if we want to navigate around.
    __terminateMediaPlayer() {
        killall --quiet "$MEDIA_PLAYER"
        return 0
    }

    if [[ $MEDIA_PLAYER == 'mpv' ]] && (( ${#fzf_output[@]} > 1 )); then
        __terminateMediaPlayer && \
        printf '%s\n' "${fzf_output[@]}" | mpv \
        --no-terminal "${mpvOptions[@]}" --playlist=-
    elif [[ $MEDIA_PLAYER == 'mpv' ]]; then
        __terminateMediaPlayer && mpv --no-terminal "${mpvOptions[@]}" "$media_file"
    else
        # Other media players may use the command line too...
        __terminateMediaPlayer && "$MEDIA_PLAYER" "$media_file"
    fi
    tput clear
}

declare -a dotdotadvice=(
    "YOU ARE IN THE HIGHEST DIRECTORY, HITTING '..' IS USELESS."
    "Hit enter on .. to go up a directotry (same as cd ..)"
)

source_file=""

# Main loop for navigation
while true; do

    disk=$(df -h "$(pwd)" | awk 'NR==2 {print $3"/"$2}')
    : "${LINES:=36}"
    : "${COLUMNS:=130}"
    : "${BACKGROUND:="#000000"}"
    : "${SEL_BACKGROUND:="#000000"}"
    : "${POINTER:="#990900"}"
    : "${PREVIEW_POS:=right}"

    # testing what's defined in fzfmrc for preview-window flipping mecanism @line 167
    if [[ $PREVIEW_POS == 'right' ]]; then
        right=left
        left=right
    else
        right=right
        left=left
    fi

    echo -ne "\e[8;${LINES};${COLUMNS}t"

    mapfile -t marker <<< "$BACKGROUND"

    declare -a bookmarks=()
    while read -r line; do
        [[ ! $line =~ '#' ]] && bookmarks+=("${line}")
    done < "${book_marks}"

    export FZF_DEFAULT_OPTS="
        --bind ctrl-a:toggle-all,ctrl-z:deselect
        --bind ctrl-b:accept,ctrl-f:first,ctrl-l:last,f12:accept
        --bind ctrl-d:accept,ctrl-e:accept,ctrl-h:accept,ctrl-p:accept
        --bind ctrl-r:accept,ctrl-t:accept,ctrl-x:accept,ctrl-y:accept
        --bind 'ctrl-w:change-preview-window($right|$left)'
        --border-label-pos=5:bottom
        --border=rounded
        --border-label='${cyn}[ ${bold}fzfm $version${nobold} ]${noc}'
        --color 'bg:$BACKGROUND,bg+:$SEL_BACKGROUND,marker:${marker[*]//[0-9]/a}'
        --color 'border:cyan,pointer:$POINTER'
        --color 'list-label:bold:red,input-label:bold:cyan,header-label:bold:cyan'
        --cycle
        --header-border=rounded
        --header-label ' selected file perms '
        --header-label-pos=top
        --info=inline-right
        --input-border=rounded
        --input-label ' filter box '
        --input-label-pos=top
        --height 100%
        --list-border=rounded
        --list-label-pos=top
        --multi
        --preview-window=$PREVIEW_POS:65%
        --pointer '|>'
        --reverse
        --scroll-off=5
    "

    if [[ $(pwd) =~ ^\/$ ]]; then
        current_dir=${PWD}
    else
        current_dir=${PWD##*/}
    fi

    # fzf preview: bat/chafa/exiftool/mediainfo for files, tree for directories
    selection=$(
        command ls -a --group-directories-first | grep -v '^.$' \
        | fzf --preview="
            if [[ $(pwd) == '/' && {} == '..' ]]; then
                echo -e ${red}'\n          ${dotdotadvice[0]}\n'${noc}
                head -29 $ascii_file
            elif [[ {} == '..' ]]; then
                echo -e ${ylw}'\n          ${dotdotadvice[1]}\n'${noc}
                head -29 $ascii_file
            elif [[ -d {} ]]; then
                tree -C {} | head -200
            elif [[ {} =~ ${IMAGE_EXTS}$ ]]; then
                chafa --colors 240 --color-space din99d \
                --size=\"\$FZF_PREVIEW_COLUMNS\"x\"\$FZF_PREVIEW_LINES\" {}
            elif [[ {} =~ ${MEDIA_EXTS}$ ]]; then
                $MEDIA_INFO {}
            elif [[ {} =~ ${OTHER_EXTS}$ ]]; then
                $FILE_INFO {}
            else
                bat --wrap=never --color=always --style=numbers --line-range :500 {}
            fi" \
            --bind "focus:transform-header:stat -c %A {}" \
            --preview-label="${cyn}[ ${bold}disk: $disk${nobold} ]${noc}" \
            --expect=f12,ctrl-b,ctrl-d,ctrl-e,ctrl-h,ctrl-p,ctrl-r,ctrl-t,ctrl-y,ctrl-x \
            --list-label " Current dir: ${current_dir} "
    )

    # If nothing selected (ESC or Ctrl-C), exit the loop
    [[ -z $selection ]] && break

    mapfile -t fzf_output <<< "$selection"
    key="${fzf_output[0]}"
    selection="${fzf_output[1]}"

    case $key in
        f12) "$FZFM_EDITOR" "$config" && source "$config"; continue ;;
        ctrl-b)
            selected_bookmark=$(
                printf '%s\n' "${bookmarks[@]}" | fzf \
                --prompt='' \
                --no-multi \
                --color 'list-label:bold:cyan' \
                --color 'preview-bg:#000000' \
                --list-label ' bookmarks ' \
                --preview-window="$PREVIEW_POS":60% \
                --preview="
                    printf '%s\n' ' Tips:' \
                    ' Bookmarks help you jump to frequently used directories quickly.'\
                    ' Add/remove bookmarks by editing ~/.config/fzfm/fzfm_bookmarks.' \
                    ' Press Enter to access the selected bookmark path.'
                "
            )
            selected_bookmark="${selected_bookmark/#~/$HOME}"
            [[ -z $selected_bookmark ]] && continue
            [[ -d $selected_bookmark ]] && cd "$selected_bookmark" || return 1
            continue
        ;;
        ctrl-d)
            tput clear
            # Get all selected items except ctrl-d
            selected_items=("${fzf_output[@]:1}")
            # Avoiding dotdot to be removed
            [[ ${fzf_output[1]} == ".." ]] && continue
            printf '\n%s\n' " ${red}Selected item(s) to remove:${noc}"
            printf '%s\n' "${selected_items[@]}"
            read -r -p " ${red}Remove these ${#selected_items[@]} items? [y/N]: ${noc}" remove
            case $remove in
                [yY])
                    rm -rf "${selected_items[@]}"
                    unset selected_items
                ;;
                *) unset selected_items ;;
            esac
            continue
        ;;
        ctrl-e)
            tput clear
            if [[ $selection =~ ${EDITOR_EXTS}$ || $OPEN_ANY == "true" ]]; then
                "$FZFM_EDITOR" "$selection"
            else
                printf '\n'
                read -r -p " ${red}Edit ${selection} with? ${noc}" alt_editor
                [[ ${alt_editor+x} ]] && "$alt_editor" "$selection"
            fi
            continue
        ;;
        ctrl-h)
            [[ $selection != "/home/$USER" ]] && {
                cd /home/"$USER" || return 1
            }
            continue
        ;;
        ctrl-p)
            (( ${#copy_buffer[@]} == 0 )) && {
                tput clear
                echo -e "\n ${red}Nothing to paste. Use copy first.${noc}" >&2
                sleep 2
                continue
            }
            for source in "${copy_buffer[@]}"; do
                base=$(basename "$source")
                dest="$(pwd)/$base"
                if [[ $source == "$dest" ]]; then
                    cp -a -- "$source" "${dest}_"
                else
                    cp -a -- "$source" "$dest"
                fi
            done
            continue
        ;;
        ctrl-r)
            tput clear
            source_file="$selection"
            printf '\n'
            read -r -p " ${grn}Rename ${source_file##*/} to: ${noc}" new_name
            [[ -z ${new_name} ]] && {
                echo " ${red}${source_file##*/} has not been renamed.${noc}"
                sleep 2
                continue
            }
            mv -f -- "${source_file}" "${new_name}"
            continue
        ;;
        ctrl-t)
            __editNewFile() {
                read -r -p " ${grn}Edit ${new_file}? [Y/n]: ${noc}" edit
                if [[ $edit =~ [yY] && -f $new_dir/$new_file ]]; then
                    "$FZFM_EDITOR" "$new_dir/$new_file"
                elif [[ $edit =~ [yY] && ! -d $new_file ]]; then
                    "$FZFM_EDITOR" "$new_file"
                fi
                unset IFS edit new_dir new_file
            }
            tput clear
            printf '\n'
            printf '%s\n' " ${grn}Use dir_name/ to create a directory," \
            " dir_name1/dir_name2/file_name for multiple subdirectories + one file," \
            " file_name1,file_name2 (comma separated) for multiple files."
            read -r -p " or simply: my_filename: ${noc}" new_file
            if [[ -z ${new_file} ]]; then
                echo " ${red}No dir_name or file_name provided...${noc}"
                sleep 2
            elif [[ $new_file =~ .+\/$ ]]; then
                new_dir="$new_file"
                mkdir -p "${new_dir}"
            elif [[ $new_file =~ .+\/+[[:alnum:]]+$ ]]; then
                new_dir=$(dirname "$new_file")
                new_file=$(basename "$new_file")
                mkdir -p "${new_dir}" && touch "$new_dir/$new_file"
                [[ -f $new_dir/$new_file ]] && __editNewFile
            elif [[ $new_file =~ ,+ ]]; then
                IFS=","; read -r -a new_files <<< "$new_file"
                for new_file in "${new_files[@]}"; do
                    touch "$new_file"
                done
                unset IFS new_file new_files
            elif [[ -f $new_file || -d $new_file ]]; then
                touch -- "${new_file}"_ && new_file="${new_file}"_
                __editNewFile
            else
                touch -- "${new_file}"
                __editNewFile
            fi
            continue
        ;;
        ctrl-y)
            declare -a copy_buffer=()
            for item in "${fzf_output[@]:1}"; do
                copy_buffer+=("$PWD/$item")
            done
            continue
        ;;
        ctrl-x)
            tput clear
            selected_items=("${fzf_output[@]:1}")
            __movePrompts() {
                case $1 in
                    --multipleItems)
                        printf '\n%s\n' " ${grn}Selected items to move:${noc}"
                        printf '%s\n' "${selected_items[@]}"
                        read -r -p " ${grn}Move to (path): ${noc}" destination
                    ;;
                    --singleItem)
                        printf '\n'
                        read -r -p " ${grn}Move ${source_file##*/} to (path): ${noc}" destination
                    ;;
                    --error)
                        printf '%s\n' " ${red}No destination provided...${noc}"
                        sleep 3
                        continue
                    ;;
                esac
                destination="${destination/#~/$HOME}"
            }
            if (( ${#selected_items[@]} > 1 )); then
                __movePrompts --multipleItems
                [[ -z ${destination} ]] && __movePrompts --error
                for item in "${selected_items[@]}"; do
                    mv -f -- "$PWD/$item" "$destination/$(basename "$item")"
                done
            else
                source_file="$PWD/$selection"
                __movePrompts --singleItem
                [[ -z ${destination} ]] && __movePrompts --error
                mv -f -- "${source_file}" "$destination/$(basename "$source_file")"
            fi
            continue
        ;;
        *) : ;;
    esac

    # Opening selected folder/file
    if [[ -d $selection ]]; then
        cd "$selection" || return 1
    elif [[ $selection =~ ${IMAGE_EXTS}$ ]]; then
        "$IMAGE_VIEWER" "$selection" & disown
    elif [[ $selection =~ ${MEDIA_EXTS}$ || $selection =~ ${PLSTS_EXTS}$ ]]; then
        _mediaPlayer "$selection" & disown
    elif [[ $selection =~ ${EDITOR_EXTS}$ || $OPEN_ANY == "true" ]]; then
        "$FZFM_EDITOR" "$selection"
    elif [[ $selection =~ ${OTHER_EXTS}$ || $OPEN_ANY == "true" ]]; then
        tput clear
        printf '\n'
        read -r -p " ${grn}Open $selection with?: " program
        case $program in
            deadbeef|ffplay|mpv|vlc)
                _mediaPlayer "$selection" & disown
            ;;
            *)
                { "$program" "$selection" & } || {
                    tput clear
                    echo -e "\n ${red}Unable to open $selection.${noc}"
                    sleep 2
                    continue
                }
            ;;
        esac
    else
    tput clear
        printf '\n'
        read -r -p " ${red}Edit ${selection}? [N/y]: ${noc}" edit
        [[ $edit =~ [yY] ]] && "$FZFM_EDITOR" "$selection"
        unset edit
    fi
    continue

done

unset current_dir
export FZF_DEFAULT_OPTS=
tput clear
