#!/usr/bin/env bash
#
# ~/.config/fzfm/fzfmrc (v0.2.18)
#
#   $$$$$$$$\  $$$$$$$$\  $$$$$$$$\  $$\      $$\
#   $$  _____| \____$$  | $$  _____| $$$\    $$$ |
#   $$ |           $$  /  $$ |       $$$$\  $$$$ |
#   $$$$$\        $$  /   $$$$$\     $$\$$\$$ $$ |
#   $$  __|      $$  /    $$  __|    $$ \$$$  $$ |
#   $$ |        $$  /     $$ |       $$ |\$  /$$ |
#   $$ |       $$$$$$$$\  $$ |       $$ | \_/ $$ |
#   \__|       \________| \__|       \__|     \__|
#                           SIMPLE FZF FILEMANAGER
#
# shellcheck disable=SC2034

# terminal size (minimun TERM_LINES=35 to display all shortcuts)
LINES=36
COLUMNS=130

# Themes are located in ~/.config/fzfm/themerc
# Available themes:
#     default c64 dark embers gruvbox jellybeans
#     molokai nord retro seoul256 solarized

THEME=default

############### FZF OPTIONS ###############
# default, "<>", ">>", "->", etc
POINTER_SHAPE=default
# left/right, if unset then default=right
PREVIEW_POS=
# value% (use quotes), if unset then default=65%
PREVIEW_WIDTH="65%"

################## TOOLS ##################
# terminal text editor (opens within fzfm)
FZFM_EDITOR=vim
IMAGE_VIEWER=sxiv
FILE_INFO=exiftool
MEDIA_INFO=mediainfo
MEDIA_PLAYER=mpv
# image preview backend used by ueberzugpp: x11, wayland, sixel, kitty, iterm2, chafa
UEBERZUG_OUTPUT=x11

############# FILE EXTENSIONS #############
EDITOR_EXTS="(.conf|.ini|.html|.json|.lua|.log|.md|.py|.sh|.toml|.txt|.xml)"
IMAGE_EXTS="(.bmp|.gif|.jpe?g|.png|.tiff|.webp)"
MEDIA_EXTS="(.aac|.avi|.flac|.mkv|.mov|.mp[3-4]?|.ogg|.wav|.webm|.wmv)"
PLSTS_EXTS="(.asx|.m3u|.pls|.ra?m|.wpl|.xspf)"
OTHER_EXTS="(.gz|.iso|.pdf|.rar|.xz|.zip|.zst)"
# be careful when opening $OTHER_EXTS or files without extension
# true/false
OPEN_ANY=false

############### MPV OPTIONS ###############
mpvOptions=(
    "--no-config" "--idle=once" "--cache=no"
    "--force-window" "--fullscreen=no"
)